executable              = submit.sh
arguments               = $(ClusterId)$(ProcId)
output                  = output/submit.$(ClusterId).$(ProcId).out
error                   = error/submit.$(ClusterId).$(ProcId).err
log                     = log/submit.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 1
request_memory = 45000
request_disk = 10000
+MaxRuntime = 24*60*60

queue
