executable              = submit.sh
arguments               = $(ClusterId)$(ProcId)
output                  = output/submit.$(ClusterId).$(ProcId).out
error                   = error/submit.$(ClusterId).$(ProcId).err
log                     = log/submit.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 1
request_memory = 24000
+MaxRuntime = 8*60

queue
